### requisicao GET/
GET http://localhost:3000
### requisicao get com parametros
GET http://localhost:3000/hackathon/6897
### requisicao POST
POST http://localhost:3000/hackathon
Content-Type: application/json

{
    "nome": "Thiago Leite",
    "telefone": "(00) 00000-0000"
}
### requisicao PUT
PUT http://localhost:3000/hackathon/239
### requisicao PATCH
PATCH http://localhost:3000/hackathon/239
### requisicao DELETE
DELETE http://localhost:3000/hackathon/239